### ISSUE TITLE
A spec that is testing Ruby's initializer

### ISSUE THREAD

**Issue by jerryjohnjacob** [peterlazar1993/aliens_rspec#1]
We don't need to test the initializer provided by Ruby, which is what is happening at https://github.com/peterlazar1993/aliens_rspec/blob/master/spec/aliens_spec.rb#L9-L11. What you can do is test that the instance variables are getting properly assigned.

**Comment by jerryjohnjacob** [comment]
In fact, the tests that are here https://github.com/peterlazar1993/aliens_rspec/blob/master/spec/aliens_spec.rb#L13-L36 are what are required in this case. They can even be compressed into a single test. The test will be asserting the setting of multiple instance variables, but I think that's what we're aiming for in the initialize method.

**Comment by peterlazar1993** [comment]
Removed test for Ruby Initializer

**Comment by peterlazar1993** [comment]
Regarding compressing it into a single test, not quite clear on how I might do that.

**Comment by peterlazar1993** [comment]
Should be fixed now.
