### ISSUE TITLE
Indentation problems in tests

### ISSUE THREAD

**Issue by jerryjohnjacob** [peterlazar1993/aliens_rspec#2]
There seem to be indentation problems in the test files.
https://github.com/peterlazar1993/aliens_rspec/blob/master/spec/aliens_spec.rb
https://github.com/peterlazar1993/aliens_rspec/blob/master/spec/alien_spec.rb

**Comment by jerryjohnjacob** [comment]
And on a similar note, there are two test files for the same class. I'm guessing one of them is no longer needed?

**Comment by peterlazar1993** [comment]
Fixed indentation and removed unused spec file
